#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HomeStat")]
	public partial class HomeStatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdaily_geo(daily_geo instance);
    partial void Updatedaily_geo(daily_geo instance);
    partial void Deletedaily_geo(daily_geo instance);
    partial void Insertmonthly_geo(monthly_geo instance);
    partial void Updatemonthly_geo(monthly_geo instance);
    partial void Deletemonthly_geo(monthly_geo instance);
    partial void Insertgeo(geo instance);
    partial void Updategeo(geo instance);
    partial void Deletegeo(geo instance);
    #endregion
		
		public HomeStatDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HomeStatConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HomeStatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeStatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeStatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HomeStatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<daily_geo> daily_geo
		{
			get
			{
				return this.GetTable<daily_geo>();
			}
		}
		
		public System.Data.Linq.Table<monthly_geo> monthly_geo
		{
			get
			{
				return this.GetTable<monthly_geo>();
			}
		}
		
		public System.Data.Linq.Table<vw_daily_fig> vw_daily_fig
		{
			get
			{
				return this.GetTable<vw_daily_fig>();
			}
		}
		
		public System.Data.Linq.Table<vw_monthly_fig> vw_monthly_fig
		{
			get
			{
				return this.GetTable<vw_monthly_fig>();
			}
		}
		
		public System.Data.Linq.Table<geo> geo
		{
			get
			{
				return this.GetTable<geo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.daily_geo")]
	public partial class daily_geo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _unique_key;
		
		private System.DateTime _created_date;
		
		private string _type;
		
		private string _borough;
		
		private System.Nullable<decimal> _lat;
		
		private System.Nullable<decimal> _lon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onunique_keyChanging(int value);
    partial void Onunique_keyChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnboroughChanging(string value);
    partial void OnboroughChanged();
    partial void OnlatChanging(System.Nullable<decimal> value);
    partial void OnlatChanged();
    partial void OnlonChanging(System.Nullable<decimal> value);
    partial void OnlonChanged();
    #endregion
		
		public daily_geo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unique_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int unique_key
		{
			get
			{
				return this._unique_key;
			}
			set
			{
				if ((this._unique_key != value))
				{
					this.Onunique_keyChanging(value);
					this.SendPropertyChanging();
					this._unique_key = value;
					this.SendPropertyChanged("unique_key");
					this.Onunique_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
		public System.DateTime created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borough", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string borough
		{
			get
			{
				return this._borough;
			}
			set
			{
				if ((this._borough != value))
				{
					this.OnboroughChanging(value);
					this.SendPropertyChanging();
					this._borough = value;
					this.SendPropertyChanged("borough");
					this.OnboroughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lon", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> lon
		{
			get
			{
				return this._lon;
			}
			set
			{
				if ((this._lon != value))
				{
					this.OnlonChanging(value);
					this.SendPropertyChanging();
					this._lon = value;
					this.SendPropertyChanged("lon");
					this.OnlonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.monthly_geo")]
	public partial class monthly_geo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _unique_key;
		
		private System.DateTime _created_date;
		
		private string _type;
		
		private string _borough;
		
		private System.Nullable<decimal> _lat;
		
		private System.Nullable<decimal> _lon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onunique_keyChanging(int value);
    partial void Onunique_keyChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnboroughChanging(string value);
    partial void OnboroughChanged();
    partial void OnlatChanging(System.Nullable<decimal> value);
    partial void OnlatChanged();
    partial void OnlonChanging(System.Nullable<decimal> value);
    partial void OnlonChanged();
    #endregion
		
		public monthly_geo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unique_key", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int unique_key
		{
			get
			{
				return this._unique_key;
			}
			set
			{
				if ((this._unique_key != value))
				{
					this.Onunique_keyChanging(value);
					this.SendPropertyChanging();
					this._unique_key = value;
					this.SendPropertyChanged("unique_key");
					this.Onunique_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
		public System.DateTime created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borough", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string borough
		{
			get
			{
				return this._borough;
			}
			set
			{
				if ((this._borough != value))
				{
					this.OnboroughChanging(value);
					this.SendPropertyChanging();
					this._borough = value;
					this.SendPropertyChanged("borough");
					this.OnboroughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lon", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> lon
		{
			get
			{
				return this._lon;
			}
			set
			{
				if ((this._lon != value))
				{
					this.OnlonChanging(value);
					this.SendPropertyChanging();
					this._lon = value;
					this.SendPropertyChanged("lon");
					this.OnlonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_daily_fig")]
	public partial class vw_daily_fig
	{
		
		private System.Xml.Linq.XElement _xml;
		
		public vw_daily_fig()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement xml
		{
			get
			{
				return this._xml;
			}
			set
			{
				if ((this._xml != value))
				{
					this._xml = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_monthly_fig")]
	public partial class vw_monthly_fig
	{
		
		private System.Xml.Linq.XElement _xml;
		
		public vw_monthly_fig()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement xml
		{
			get
			{
				return this._xml;
			}
			set
			{
				if ((this._xml != value))
				{
					this._xml = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cau.geo")]
	public partial class geo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UNIQUE_KEY;
		
		private System.DateTime _CREATED_DATE;
		
		private System.Nullable<System.DateTime> _CLOSED_DATE;
		
		private string _AGENCY;
		
		private string _COMPLAINT_TYPE;
		
		private string _DESCRIPTOR_1;
		
		private string _INCIDENT_ADDRESS;
		
		private System.Nullable<decimal> _LAT;
		
		private System.Nullable<decimal> _LON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUNIQUE_KEYChanging(int value);
    partial void OnUNIQUE_KEYChanged();
    partial void OnCREATED_DATEChanging(System.DateTime value);
    partial void OnCREATED_DATEChanged();
    partial void OnCLOSED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCLOSED_DATEChanged();
    partial void OnAGENCYChanging(string value);
    partial void OnAGENCYChanged();
    partial void OnCOMPLAINT_TYPEChanging(string value);
    partial void OnCOMPLAINT_TYPEChanged();
    partial void OnDESCRIPTOR_1Changing(string value);
    partial void OnDESCRIPTOR_1Changed();
    partial void OnINCIDENT_ADDRESSChanging(string value);
    partial void OnINCIDENT_ADDRESSChanged();
    partial void OnLATChanging(System.Nullable<decimal> value);
    partial void OnLATChanged();
    partial void OnLONChanging(System.Nullable<decimal> value);
    partial void OnLONChanged();
    #endregion
		
		public geo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIQUE_KEY", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UNIQUE_KEY
		{
			get
			{
				return this._UNIQUE_KEY;
			}
			set
			{
				if ((this._UNIQUE_KEY != value))
				{
					this.OnUNIQUE_KEYChanging(value);
					this.SendPropertyChanging();
					this._UNIQUE_KEY = value;
					this.SendPropertyChanged("UNIQUE_KEY");
					this.OnUNIQUE_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSED_DATE
		{
			get
			{
				return this._CLOSED_DATE;
			}
			set
			{
				if ((this._CLOSED_DATE != value))
				{
					this.OnCLOSED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CLOSED_DATE = value;
					this.SendPropertyChanged("CLOSED_DATE");
					this.OnCLOSED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENCY", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string AGENCY
		{
			get
			{
				return this._AGENCY;
			}
			set
			{
				if ((this._AGENCY != value))
				{
					this.OnAGENCYChanging(value);
					this.SendPropertyChanging();
					this._AGENCY = value;
					this.SendPropertyChanged("AGENCY");
					this.OnAGENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLAINT_TYPE", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string COMPLAINT_TYPE
		{
			get
			{
				return this._COMPLAINT_TYPE;
			}
			set
			{
				if ((this._COMPLAINT_TYPE != value))
				{
					this.OnCOMPLAINT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._COMPLAINT_TYPE = value;
					this.SendPropertyChanged("COMPLAINT_TYPE");
					this.OnCOMPLAINT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTOR_1", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string DESCRIPTOR_1
		{
			get
			{
				return this._DESCRIPTOR_1;
			}
			set
			{
				if ((this._DESCRIPTOR_1 != value))
				{
					this.OnDESCRIPTOR_1Changing(value);
					this.SendPropertyChanging();
					this._DESCRIPTOR_1 = value;
					this.SendPropertyChanged("DESCRIPTOR_1");
					this.OnDESCRIPTOR_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCIDENT_ADDRESS", DbType="VarChar(40)")]
		public string INCIDENT_ADDRESS
		{
			get
			{
				return this._INCIDENT_ADDRESS;
			}
			set
			{
				if ((this._INCIDENT_ADDRESS != value))
				{
					this.OnINCIDENT_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._INCIDENT_ADDRESS = value;
					this.SendPropertyChanged("INCIDENT_ADDRESS");
					this.OnINCIDENT_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAT", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> LAT
		{
			get
			{
				return this._LAT;
			}
			set
			{
				if ((this._LAT != value))
				{
					this.OnLATChanging(value);
					this.SendPropertyChanging();
					this._LAT = value;
					this.SendPropertyChanged("LAT");
					this.OnLATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LON", DbType="Decimal(9,7)")]
		public System.Nullable<decimal> LON
		{
			get
			{
				return this._LON;
			}
			set
			{
				if ((this._LON != value))
				{
					this.OnLONChanging(value);
					this.SendPropertyChanging();
					this._LON = value;
					this.SendPropertyChanged("LON");
					this.OnLONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
